name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@master

      - name: Install Flex
        run: deno install -Af src/flex.ts

      - name: Append deno bin folder to PATH
        run: echo "::set-env name=PATH::/home/runner/.deno/bin:$PATH"
        if: matrix.os == 'ubuntu-latest'

      - name: Append deno bin folder to PATH
        run: echo "::set-env name=PATH::/Users/runner/.deno/bin:$PATH"
        if: matrix.os == 'macOS-latest'

      - name: Append deno bin folder to PATH
        run: echo "::add-path::C:\Users\runneradmin\.deno\bin"
        if: matrix.os == 'windows-latest'

      - name: Run tests
        run: deno test --allow-read --allow-run
